# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Build
on:
  push:
    branches:
      - main
jobs:
  linux:
    defaults:
      run:
        working-directory: '~/repo'
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: restore_cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: v2-dependencies-linux-{{ checksum "package.json" }}
          restore-keys: |-
            v2-dependencies-linux-{{ checksum "package.json" }}
            v2-dependencies-liux-
          path: node_modules
      - run: npm install
      - run: npm test
  windows:
    defaults:
      run:
        working-directory: '~/repo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: restore_cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: v2-dependencies-win-{{ checksum "package.json" }}
          restore-keys: |-
            v2-dependencies-win-{{ checksum "package.json" }}
            v2-dependencies-win-
          path: node_modules
      - run: npm install
      - run: npm test
